baseurl = "http://mattjarvis.org.uk/"
languageCode = "en-us"
title = "Nothing to see here"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-89572020-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "www-mattjarvis-org-uk"

[params]
	name = "Matt Jarvis"
	description = "That rug really tied the room together"
	bio = "Cloud Builder - Systems Monkey"
	# Enter optionally your twitter account
	twitter = "mattj_io"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Yeah, well, you know, that's just, like, your opinion, man."
	tweet = ""
	share = ""
	# 404 page
	title404 = "I'm sorry Dave, I'm afraid I can't do that"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/mattj_io"
    github   = "https://www.github.com/mattj-io"
    linkedin  = "https://uk.linkedin.com/in/mattjarvis08"

